= EnMail

image:https://img.shields.io/gem/v/enmail.svg[
	Gem Version, link="https://rubygems.org/gems/enmail"]
image:https://travis-ci.org/riboseinc/enmail.svg?branch=master[
	Build Status, link="https://travis-ci.org/riboseinc/enmail"]
image:https://img.shields.io/codecov/c/github/riboseinc/enmail.svg[
	Test Coverage, link="https://codecov.io/gh/riboseinc/enmail"]
image:https://img.shields.io/codeclimate/github/riboseinc/enmail.svg[
	"Code Climate", link="https://codeclimate.com/github/riboseinc/enmail"]

EnMail (Encrypted mail) helps the Ruby mail gem send secure encrypted messages.

Currently, only OpenPGP is supported, either via GPGME or RNP.

== Basic usage

Given some e-mail:

[source,ruby]
----
mail = Mail.new
mail.from = "Very Myself <me@example.com>"
mail.to = "Someone Else <someone@example.com>"
mail.subject = "It is very important"
mail.body = "Or, whatever"

adapter = ::EnMail::Adapters::RNP

# sign message
EnMail.protect :sign, mail, adapter: adapter

# encrypt message
EnMail.protect :encrypt, mail, adapter: adapter

# sign and encrypt message
EnMail.protect :sign_and_encrypt_encapsulated, mail, adapter: adapter

# or
EnMail.protect :sign_and_encrypt_combined, mail, adapter: adapter
----

== Development

=== Setup

Clone the repository.

[source,sh]
----
git clone https://github.com/riboseinc/enmail
----

NOTE: GnuPG will create UNIX sockets in the `<project_root>/tmp/pgp_home`
directory.  Be advised that paths to UNIX sockets have limited length (about 100
characters).  Therefore, please ensure that path to directory you are cloning
repository into is less than 50 characters long, or you may experience weird
errors.

Setup your environment.

[source,sh]
----
bin/setup
----

Above one will take a short while.  As the final step, tests will be run
in order to prove your setup's correctness.

=== Regenerating OpenPGP keys

If you ever need to regenerate your development OpenPGP keys:

1. `rm -rf <project_root>/tmp`
2. `bundle exec rake generate_pgp_keys`

NOTE: Always run tests after pulling new changes from the upstream.  If they
fail, it's likely that OpenPGP keys should be regenerated.

== Contributing

First, thank you for contributing! We love pull requests from everyone.
By participating in this project, you hereby grant
https://www.ribose.com[Ribose Inc.] the right to grant or transfer an
unlimited number of non exclusive licenses or sub-licenses to third
parties, under the copyright covering the contribution to use the
contribution by all means.

Here are a few technical guidelines to follow:

1.  Open an https://github.com/abunashir/enmail/issues[issue] to discuss
a new feature.
2.  Write tests to support your new feature.
3.  Make sure the entire test suite passes locally and on CI.
4.  Open a Pull Request.
5.  https://github.com/thoughtbot/guides/tree/master/protocol/git#write-a-feature[Squash
your commits] after receiving feedback.
6.  Party!

== Credits

This gem is developed, maintained and funded by
https://www.ribose.com[Ribose Inc.]

== License

This gem is licensed under MIT license.
