= EnMail

image:https://img.shields.io/gem/v/enmail.svg[
	Gem Version, link="https://rubygems.org/gems/enmail"]
image:https://img.shields.io/travis/riboseinc/enmail/master.svg[
	Build Status, link="https://travis-ci.org/riboseinc/enmail/branches"]
image:https://img.shields.io/codecov/c/github/riboseinc/enmail.svg[
	Test Coverage, link="https://codecov.io/gh/riboseinc/enmail"]
image:https://img.shields.io/codeclimate/maintainability/riboseinc/enmail.svg[
	"Code Climate", link="https://codeclimate.com/github/riboseinc/enmail"]

EnMail (encrypted mail) signs or encrypts correspondence sent via the Ruby
https://rubygems.org/gems/mail[mail] gem.

EnMail has open architecture.  Multiple adapters are supported, and new ones
can be implemented with ease.  Currently, GPGME and RNP adapters are available
out of the box.  Both implement OpenPGP standard.

== Basic usage

Given some e-mail:

[source,ruby]
----
mail = Mail.new
mail.from = "Very Myself <me@example.com>"
mail.to = "Someone Else <someone@example.com>"
mail.subject = "It is very important"
mail.body = "Or, whatever"

adapter = ::EnMail::Adapters::RNP

# sign message
EnMail.protect :sign, mail, adapter: adapter

# encrypt message
EnMail.protect :encrypt, mail, adapter: adapter

# sign and encrypt message
EnMail.protect :sign_and_encrypt_encapsulated, mail, adapter: adapter

# or
EnMail.protect :sign_and_encrypt_combined, mail, adapter: adapter
----

== Adapters

=== RNP

`RNP` adapter provides OpenPGP-compliant cryptography via
https://www.rnpgp.com/[RNP] library.

==== Dependencies

This adapter requries two additional pieces of software to be installed:

1. RNP library, version 0.9.2 or newer
2. `https://rubygems.org/gems/rnp[rnp]` gem, version 1.0.1 or newer

==== Options

Following adapter-specific options are supported:

`homedir`::
Optional.  Path to RNP home directory, which contains public and secret
keyrings.  In most situations, RNP is able to read GnuPG home directories,
hence it's common to set it to `<your_home_directory>/.gpg`.  Defaults to
`<your_home_directory>/.rnp`.
`signer`::
Optional.  User id or e-mail which identifies key which will be used for message
signing.  By default, first address from mail's From field is used.
`key_password`::
Optional.  Password for signer's key.  Can be a string or proc, see
`rnp` gem documentation for `Rnp#password_provider=`.

=== GPGME

`GPGME` adapter provides OpenPGP-compliant cryptography via
https://gnupg.org/software/gpgme/index.html[GnuPG Made Easy] library.

==== Dependencies

This adapter requries two additional pieces of software to be installed:

1. GnuPG, version 2.2
2. `https://rubygems.org/gems/gpgme[gpgme]` gem

==== Options

Following adapter-specific options are supported:

`signer`::
Optional.  User id or e-mail which identifies key which will be used for message
signing.  By default, first address from mail's From field is used.
`key_password`::
Optional.  Password for signer's key.  Must be a string.

==== Caveats

If you want to use home directory in a non-standard location, change it for
whole GPGME in following way: `GPGME::Engine.home_dir = 'path/to/home_dir'`

== Development

=== Setup

Clone the repository.

[source,sh]
----
git clone https://github.com/riboseinc/enmail
----

NOTE: GnuPG will create UNIX sockets in the `<project_root>/tmp/pgp_home`
directory.  Be advised that paths to UNIX sockets have limited length (about 100
characters).  Therefore, please ensure that path to directory you are cloning
repository into is less than 50 characters long, or you may experience weird
errors.

Setup your environment.

[source,sh]
----
bin/setup
----

Above one will take a short while.  As the final step, tests will be run
in order to prove your setup's correctness.

=== Regenerating OpenPGP keys

If you ever need to regenerate your development OpenPGP keys, execute:

[source,sh]
----
bundle exec rake pgp_keys:regenerate
----

NOTE: Always run tests after pulling new changes from the upstream.  If they
fail, it's likely that OpenPGP keys should be regenerated.

=== Contributing

First, thank you for contributing! We love pull requests from everyone.
By participating in this project, you hereby grant
https://www.ribose.com[Ribose Inc.] the right to grant or transfer an
unlimited number of non exclusive licenses or sub-licenses to third
parties, under the copyright covering the contribution to use the
contribution by all means.

Here are a few technical guidelines to follow:

1.  Open an https://github.com/abunashir/enmail/issues[issue] to discuss
    a new feature.
2.  Write tests to support your new feature.
3.  Make sure the entire test suite passes locally and on CI.
4.  Open a Pull Request.
5.  After receiving feedback, perform
    https://help.github.com/articles/about-git-rebase/[an interactive rebase]
    on your branch, in order to create a series of cohesive commits with
    descriptive messages.
6.  Party!

== Credits

This gem is developed, maintained and funded by
https://www.ribose.com[Ribose Inc.]

== License

This gem is licensed under MIT license.
