= RNP Adapter Guide

`RNP` adapter provides OpenPGP-compliant cryptography via
https://www.rnpgp.com/[RNP] library.

== Dependencies

This adapter requries two additional pieces of software to be installed:

1. RNP library, version 0.9.2 or newer
2. `https://rubygems.org/gems/rnp[rnp]` gem, version 1.0.1 or newer

== Options

Following adapter-specific options are supported:

`homedir`::
Optional.  Path to RNP home directory, which contains public and secret
keyrings.  In most situations, RNP is able to read GnuPG home directories,
hence it's common to set it to `<your_home_directory>/.gpg`.  Defaults to
`<your_home_directory>/.rnp`.
`signer`::
Optional.  User id or e-mail which identifies key which will be used for message
signing.  By default, first address from mail's From field is used.
`key_password`::
Optional.  Password for signer's key.  Can be a string or proc, see
`rnp` gem documentation for `Rnp#password_provider=`.

== Issue tracker

Bugs, feature requests, and other issues are tracked with `adapter: rnp`
label: https://github.com/riboseinc/enmail/issues?q=is%3Aissue+is%3Aopen+label%3A%22adapter%3A+rnp%22
